### PR TITLE
Rails 7.2 support

### PR DESCRIPTION
**Pull request by jprosevear**

### CODE REVIEW

**Comment by jprosevear** [comment]
Initial attempt, but currently blocked because mongoid has no 7.2 support

**Comment by jprosevear** [comment]
https://github.com/mongodb/mongoid/pull/5852

**Comment by jprosevear** [comment]
> [mongodb/mongoid#5852](https://github.com/mongodb/mongoid/pull/5852)

Still waiting on upstream merge.

**Comment by jprosevear** [comment]
> > [mongodb/mongoid#5852](https://github.com/mongodb/mongoid/pull/5852)
> 
> Still waiting on upstream merge.

Merged; hopefully release shortly, otherwise I'll use github verison.

**Comment by simukappu** [comment]
Have you checked if all tests passed?

**Comment by jprosevear** [comment]
> Have you checked if all tests passed?

I have not, but the mongo changes look minimal.  I will try it directly if there is no release soon

**Comment by jprosevear** [comment]
Mongoid has bumped release numbers; waiting for gems

**Comment by jprosevear** [comment]
@simukappu ok mongoid 8.1.6 is out;  do you want to retrigger a rebuild for this and / or your development branch

**Comment by jprosevear** [comment]
Building in my fork: https://github.com/codalio/activity_notification/actions/runs/10963455543/job/30444974349

**Pull request closed without merging**
