### PR TITLE
Pass the entire options of notify to notification_targets

### PR DESCRIPTION
**Pull request by euanlau**
Hey @simukappu,

This pull request changes `notification_targets` to take the entire options of `notify` instead of just `key` alone.
We need this in our application since we ran into a few cases where the targets needed to be computed based on parameters that are not part of the model itself. 

Please take a look and let me know what you think.

Cheer!

### CODE REVIEW

**Comment by simukappu** [comment]
Hi @euanlau 

This is a really good enhancement. The only concern is compatibility with older version for existing users.
Could you update this pull request as following feedback?
1. Make `Notifiable#notification_targets# able to receive both of *key* as string and *options* as Hash.
2. Write tests for these two cases.
3. Send this pull request to *development* branch.

Thank you for your contribution!

**Comment by euanlau** [comment]
@simukappu Sure! Let me update this PR.

**Comment by euanlau** [comment]
I have a question. Isn't `Notifiable#notification_targets` a private method of notifiable? We have to pass the `options` to the user defined `targets` field or the custom notification targets method in order to expose the `options`. How do we determine when to pass the options or the key alone?

**Comment by simukappu** [comment]
Thank you @euanlau.
You are right, we cannot determine whether `NotificationApi#notify` method should pass the options or the key alone to `Notifiable#notification_targets`. We can handle this by adding some kind of configurations of options to `NotificationApi#notify` method, but it may be too complex.
Let me think about it.

**Comment by euanlau** [comment]
@simukappu Sounds good. Keep me posted. I also want to use this opportunity to say thank you. This is a great gem! 👍

**Comment by simukappu** [comment]
Thank you @euanlau, I appreciate it.
I tried to add *pass_full_options* option to *NotificationApi#notify*. You can pass the entire options to *notification_targets* with this option like this:
```
@comment.notify(:users, key: 'sample_key', your_param: 'yeah', pass_full_options: true)
```
I have sent a pull request including your commits to your repository: https://github.com/euanlau/activity_notification/pull/1.
What do you think?

**Comment by euanlau** [comment]
@simukappu Looks good! That's the only way to support backward compatibility it seems.

**Comment by euanlau** [comment]
I merged your PR. Thanks a lot for your help!

**Comment by simukappu** [comment]
I have merged your PR and also merged it to master branch.
Please use this from master branch before new version will be released.
Thank you again for your contribution!

**Pull request merged**
