### PR TITLE
Fix ruby 2.7 deprecation warnings

### PR DESCRIPTION
**Pull request by szechyjs**
**Issue #122**

### Summary

Fix the deprecation warnings for ruby 2.7

### CODE REVIEW

**Comment by onshi** [comment]
Hey @szechyjs, awesome job fixing those warnings 🙇‍♂️ 

Would you also consider fixing a couple more by pulling my patch into your PR or would you rather prefer that I open PR against your branch? 
Patch:

[activity_notification_patch.txt](https://github.com/simukappu/activity_notification/files/4779507/activity_notification_patch.txt)

I think that I also found out one edge case with hash deprecation warnings in `lib/activity_notification/common.rb` which is covered by this test case:

```ruby
it "returns specified symbol with controller and additional arguments including hash as last argument" do
  module AdditionalMethods
    def custom_method(controller, key, options:)
      controller == 'StubController' and key == 'test1.key' ? 1 : 0
    end
  end
  test_instance.extend(AdditionalMethods)
  expect(ActivityNotification.resolve_value(test_instance, :custom_method, 'test1.key', options: 1)).to eq(1)
  expect(ActivityNotification.resolve_value(test_instance, :custom_method, 'test2.key', options: 1)).to eq(0)
end
```

I added handling it in `lib/activity_notification/common.rb:19` 
```ruby
if args.last.kind_of?(Hash)
  symbol_method.call(ActivityNotification.get_controller, *args[0...-1], **args.last)
else
  symbol_method.call(ActivityNotification.get_controller, *args)
end
```

and used the same approach at `lib/activity_notification/common.rb:81`. 
If this is not the desired solution I could think about a different approach.

This will leave us with following deprecation warnings:

```
ruby/2.7.0/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/test_case.rb:394: warning: The called method `get' is defined here
ruby/2.7.0/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/test_case.rb:402: warning: The called method `post' is defined here
ruby/2.7.0/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/test_case.rb:420: warning: The called method `delete' is defined here
ruby/2.7.0/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/test_case.rb:414: warning: The called method `put' is defined here
ruby/2.7.0/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/testing/integration.rb:352: warning: The called method is defined here
```

which will be fixed when a release for `rails-controller-testing#1.0.5` would happen https://github.com/rails/rails-controller-testing/issues/60

@simukappu (sorry for shameless ping) do you think we are close to releasing a new version of the gem? 

Best, 
Jan

**Comment by simukappu** [comment]
@szechyjs Thank you for your patch!

@onshi Thank you so much for your dive deep into fixing this ruby 2.7 deprecation. As you know, we have still several deprecation warning in RSpec testing. Could you give us your patch as pull request?

**Comment by onshi** [comment]
@simukappu sure, no problem at all I will prepare PR this week. Should I also pull @szechyjs changes or would you rather keep PRs separated?

**Comment by simukappu** [comment]
Thank you so much for your contribution! BTW, [Ruby 2.7.2 has been released](https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/) and deprecation warnings about keyword argument changes are off by default. Let me consider a little more about this changes for *activity_notification*.

**Comment by simukappu** [comment]
LGTM.

**Pull request merged**
