### PR TITLE
Add key uniqueness validation

### PR DESCRIPTION
**Pull request by irondnb**
- validation for uniqueness of key-target in Subscription model

- move create_subbscription method to build_subscription, so we can check for errors before save without rising exception

- left create_subbscription method for test purposes 

- refactor some test: lazy loading objects

### CODE REVIEW

**Comment by irondnb** [comment]
working on tests

**Comment by simukappu** [comment]
As you mentioned, we need to add validation for uniqueness of key-target to Subscription model. Let me know when your work complete.
Thank you for your contribution!

**Comment by simukappu** [comment]
As you mentioned, we need to add validation for uniqueness of key-target to Subscription model. Let me know when your work completes.
Thank you for your contribution!

**Comment by irondnb** [comment]
@simukappu Yep, its still unfinished. The bigest impediment here is dynamodb, which doesn't support uniqueness and can't guarantee that. Since, i don't have any experience with that database, i'm still messing around to make it work. Some advice will be appreciated

https://aws.amazon.com/blogs/database/simulating-amazon-dynamodb-unique-constraints-using-transactions/
https://stackoverflow.com/questions/12920884/is-there-a-way-to-enforce-unique-constraint-on-a-property-field-other-than-the

**Comment by simukappu** [comment]
Hi @irondnb,
Could you squash your commits into one?

**Comment by irondnb** [comment]
@simukappu I've tried, but it end up in more commits :face_with_head_bandage:
I will just create another PR with new branch.

Note: I've drop support for dynamodb for now and will fix it in another PR

**Comment by simukappu** [comment]
I've rewrite your contribution and pushed as this commit: https://github.com/simukappu/activity_notification/commit/3b46954a3ea6cd9964097b006f748bbeee7552e7
Also added dynamoid uniqueness  validation.

Thank you for your contribution!

**Pull request closed without merging**
